server:  
  port: 2018
  
  
  
spring:
  redis:
    host: 127.0.0.1
    port: 5086
    password: 1993
    pool:
      max-idle: 100
      min-idle: 10
      max-wait: 100000
      
  datasource:
    url: jdbc:mysql://localhost:3306/pms?useUnicode=true&characterEncoding=utf8
    username : root
    password : root
    driver-class-name: com.mysql.jdbc.Driver
   
mybatis:
  type-aliases-package : com.pms.masterdata.entity
  mapper-locations: classpath:mapper/*.xml
  
  
  

